title: Arasu RRK
url: "https://arasu-rrk.com"
baseurl:
google_analytics_key: UA-92684325-1
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Professional .NET web developer, currently working in Syncfusion Inc.

# Author details for the jekyll-seo-tag gem
author:
  name: Arasu RRK
  email:
  twitter: 

# Social details for the jekyll-seo-tag gem
social:
  name: Arasu RRK
  links:
    - https://arasu-rrk.com

collections:
  staff_members:
    output: false
  clients:
    output: false

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
