# Site
name: Arasu RRK
title: Arasu RRK
url: "https://arasu-rrk.com"
baseurl:
favicon: "favicon.ico"
google_analytics_key: UA-92684325-1
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Professional .NET web developer, currently working in Syncfusion Inc.

include: ["_pages"]

# Author details for the jekyll-seo-tag gem
authors:
    arasu_rrk:
      name:           Arasu RRK
      site:           https://arasu-rrk.com
      avatar:         images/me/rrk-black-white.jpeg
      bio:            "Hi, I'm Arasu RRK."
      email:          hello@arasu-rrk.com
      twitter:        https://twitter.com/arasu_rrk


# Social details for the jekyll-seo-tag gem
social:
  name: Arasu RRK
  links:
    - https://arasu-rrk.com

collections:
  staff_members:
    output: false
  clients:
    output: false

paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"
  - "jekyll-redirect-from"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
